execution:
    uuid: 793080cc-4078-4179-bfb7-f1812e0113f3
    runtime:
        start: 2020-11-09T07:40:33.112475+00:00
        end: 2020-11-09T07:40:34.244387+00:00
        duration: 1 second, and 131912 microseconds

action:
    type: import
    format: CasavaOneEightSingleLanePerSampleDirFmt
    manifest:
    -   name: L1S105_9_L001_R1_001.fastq.gz
        md5sum: 385b11f67317a90a9b970af9b99a4beb
    -   name: L1S140_6_L001_R1_001.fastq.gz
        md5sum: 630cd0a5fc10c9b2a76e319e79a7dfc8
    -   name: L1S208_10_L001_R1_001.fastq.gz
        md5sum: d892a3cf05bd531e106e800466f5e106
    -   name: L1S257_11_L001_R1_001.fastq.gz
        md5sum: b3e87ec83c8cddedde96695ea9165b7b
    -   name: L1S281_5_L001_R1_001.fastq.gz
        md5sum: 11ca8c598a0ffffa6048e060cc9dae72
    -   name: L1S57_13_L001_R1_001.fastq.gz
        md5sum: 0793c3162c85370681bb8706bf14895e
    -   name: L1S76_12_L001_R1_001.fastq.gz
        md5sum: bc7b3d614c3ed830801c5c384f536e12
    -   name: L1S8_8_L001_R1_001.fastq.gz
        md5sum: 0290cbe020ac5bcb537fd5b8668489e8
    -   name: L2S155_25_L001_R1_001.fastq.gz
        md5sum: c8df31e4a2d34a94e5938bd2ca157836
    -   name: L2S175_27_L001_R1_001.fastq.gz
        md5sum: 06c96dc623987d8fbb9fc6214de535d9
    -   name: L2S204_1_L001_R1_001.fastq.gz
        md5sum: eba09f15b70d8e4a2207caf60e4dac05
    -   name: L2S222_23_L001_R1_001.fastq.gz
        md5sum: 0bfc7d99ff106d473c8885f8f6cd55e6
    -   name: L2S240_7_L001_R1_001.fastq.gz
        md5sum: 63fe1978ceba4b2306e82a4664cf15d8
    -   name: L2S309_33_L001_R1_001.fastq.gz
        md5sum: 3182db150ee973d0c6c7cd9d51f2b773
    -   name: L2S357_15_L001_R1_001.fastq.gz
        md5sum: 171e2622df6979cdc3afffda3b911091
    -   name: L2S382_34_L001_R1_001.fastq.gz
        md5sum: 7d87c88229e1ec2e0da9d9beeeed30af
    -   name: L3S242_19_L001_R1_001.fastq.gz
        md5sum: 7fc65574c51c3e8b7717f1dba3ccd83e
    -   name: L3S294_16_L001_R1_001.fastq.gz
        md5sum: d97bc88d0cfe55aba600cea3068e2272
    -   name: L3S313_32_L001_R1_001.fastq.gz
        md5sum: 750b7e423184635045bc21bd8a8db9d2
    -   name: L3S341_18_L001_R1_001.fastq.gz
        md5sum: dfb992d067ba64b81a7477ce4bb9e79b
    -   name: L3S360_4_L001_R1_001.fastq.gz
        md5sum: 1e09c86c54201df69b6a7c6c83fc6b4c
    -   name: L3S378_24_L001_R1_001.fastq.gz
        md5sum: 013d481189e1045692e31887ab5c9982
    -   name: L4S112_26_L001_R1_001.fastq.gz
        md5sum: 73a8282031dd520d083948fab7690b42
    -   name: L4S137_21_L001_R1_001.fastq.gz
        md5sum: 65fa8110fe061e3a82884711518fb604
    -   name: L4S63_31_L001_R1_001.fastq.gz
        md5sum: 57273dca6dc977178865b50b4fe94f38
    -   name: L5S104_28_L001_R1_001.fastq.gz
        md5sum: 9713af384276a26b5a83a56981c92d06
    -   name: L5S155_2_L001_R1_001.fastq.gz
        md5sum: 48699cf762713496ef594151df47edbc
    -   name: L5S174_29_L001_R1_001.fastq.gz
        md5sum: eb2aa52ccdb5c128c32089bdbbe6ad5e
    -   name: L5S203_3_L001_R1_001.fastq.gz
        md5sum: 620a45967e77391e647c52c6709db8fe
    -   name: L5S222_17_L001_R1_001.fastq.gz
        md5sum: 93f805ffeefef8adf7c2660b316f5932
    -   name: L5S240_14_L001_R1_001.fastq.gz
        md5sum: 4b1672bcfe538e27a12988aa31b65b69
    -   name: L6S20_20_L001_R1_001.fastq.gz
        md5sum: 27d64b45a69917486526eddb4e40badf
    -   name: L6S68_30_L001_R1_001.fastq.gz
        md5sum: 6b3166516b94373a21d6ae1265f8eff3
    -   name: L6S93_22_L001_R1_001.fastq.gz
        md5sum: b6e8e66c9539f5b79ff04e844a435d2f

transformers:
    output:
    -   from: CasavaOneEightSingleLanePerSampleDirFmt
        to: SingleLanePerSampleSingleEndFastqDirFmt
        plugin: !ref 'environment:plugins:types'

environment:
    platform: linux-x86_64
    python: |-
        3.6.7 | packaged by conda-forge | (default, Nov  6 2019, 16:19:42)
        [GCC 7.3.0]
    framework:
        version: 2019.10.0
        website: https://qiime2.org
        citations:
        - !cite 'framework|qiime2:2019.10.0|0'
    plugins:
        types:
            version: 2019.10.0
            website: https://github.com/qiime2/q2-types
    python-packages:
        zipp: 0.6.0
        xopen: 0.8.4
        widgetsnbextension: 3.5.1
        wheel: 0.33.6
        webencodings: 0.5.1
        wcwidth: 0.1.7
        urllib3: 1.25.6
        unifrac: 0.10.0
        tzlocal: 2.0.0
        traitlets: 4.3.3
        tornado: 6.0.3
        testpath: 0.4.2
        terminado: 0.8.2
        statsmodels: 0.10.1
        six: 1.12.0
        setuptools: 41.6.0.post20191101
        sepp: 4.3.10
        Send2Trash: 1.5.0
        seaborn: 0.9.0
        scipy: 1.3.1
        scikit-learn: 0.21.2
        scikit-bio: 0.5.5
        requests: 2.22.0
        qiime2: 2019.10.0
        qiime-2-ll-quick-viewer: 0.2.8
        q2templates: 2019.10.0
        q2cli: 2019.10.0
        q2-vsearch: 2019.10.0
        q2-types: 2019.10.0
        q2-taxa: 2019.10.0
        q2-sample-classifier: 2019.10.0
        q2-quality-filter: 2019.10.0
        q2-quality-control: 2019.10.0
        q2-phylogeny: 2019.10.0
        q2-metadata: 2019.10.0
        q2-longitudinal: 2019.10.0
        q2-gneiss: 2019.10.0
        q2-fragment-insertion: 2019.10.0
        q2-feature-table: 2019.10.0
        q2-feature-classifier: 2019.10.0
        q2-emperor: 2019.10.0
        q2-diversity: 2019.10.0
        q2-demux: 2019.10.0
        q2-deblur: 2019.10.0
        q2-dada2: 2019.10.0
        q2-cutadapt: 2019.10.0
        q2-composition: 2019.10.0
        q2-alignment: 2019.10.0
        pyzmq: 18.1.0
        PyYAML: 5.1.2
        pytz: '2019.3'
        python-dateutil: 2.8.0
        pytest: 5.2.2
        PySocks: 1.7.1
        pyrsistent: 0.15.5
        pyparsing: 2.4.2
        pyOpenSSL: 19.0.0
        Pygments: 2.4.2
        pycparser: '2.19'
        py: 1.8.0
        ptyprocess: 0.6.0
        psutil: 5.6.3
        prompt-toolkit: 2.0.10
        prometheus-client: 0.7.1
        pluggy: 0.12.0
        pip: 19.3.1
        Pillow: 6.2.1
        pickleshare: 0.7.5
        pexpect: 4.7.0
        patsy: 0.5.1
        parso: 0.5.1
        pandocfilters: 1.4.2
        pandas: 0.25.2
        packaging: '19.2'
        olefile: '0.46'
        numpy: 1.18.1
        notebook: 6.0.1
        nose: 1.3.7
        networkx: '2.4'
        nbformat: 4.4.0
        nbconvert: 5.6.1
        natsort: 6.0.0
        msgpack: 0.6.2
        more-itertools: 7.2.0
        mistune: 0.8.4
        matplotlib: 3.1.0
        MarkupSafe: 1.1.1
        lockfile: 0.12.2
        kiwisolver: 1.1.0
        jupyter-core: 4.5.0
        jupyter-client: 5.3.3
        jsonschema: 3.1.1
        joblib: 0.14.0
        Jinja2: 2.10.3
        jedi: 0.15.1
        ipywidgets: 7.5.1
        ipython: 7.9.0
        ipython-genutils: 0.2.0
        ipykernel: 5.1.3
        importlib-metadata: '0.23'
        ijson: '2.5'
        idna: '2.8'
        hdmedians: '0.13'
        h5py: 2.10.0
        gneiss: 0.4.6
        future: 0.18.2
        fastcluster: 1.1.25
        entrypoints: '0.3'
        emperor: 1.0.0b20
        dnaio: 0.4.1
        DendroPy: 4.4.0
        defusedxml: 0.6.0
        decorator: 4.4.1
        deblur: 1.1.0
        Cython: 0.29.13
        cycler: 0.10.0
        cutadapt: '2.6'
        cryptography: '2.7'
        Click: '7.0'
        chardet: 3.0.4
        cffi: 1.13.1
        certifi: 2019.11.28
        CacheControl: 0.12.5
        bokeh: 1.3.4
        bleach: 3.1.0
        biom-format: 2.1.7
        bibtexparser: 1.1.0
        backcall: 0.1.0
        attrs: 19.3.0
        atomicwrites: 1.3.0
        asn1crypto: 1.2.0
